# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'ImageClassification' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageClassification
   pod 'TensorFlowLiteSwift'
   pod 'ReachabilityManager'
   pod 'FileMD5Hash'
   pod 'SSZipArchive'
   pod 'Firebase/MLVision'
   pod 'Firebase/MLVisionTextModel'
   pod 'Firebase/MLVisionBarcodeModel'
   pod 'SSZipArchive'
end
